spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  mail:
    host: smtp.sina.com
    username: imcaidoge@sina.com
    password: 53244ce859f5d93f
    protocol: smtps
    properties:
      auth: true
      port: 465 #465或者994
      starttls:
        enable: true
        required: true
      ssl:
        enable: true

mybatis:
  type-aliases-package: com.jing.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #    ????
    map-underscore-to-camel-case: true
    use-generated-keys: true
#logging:
#  level:
#    com.jing: debug
#  file:
#    name: F:/java-project-workspace/community/data/community.log
community:
  path:
    domain: http://localhost:8080
    upload: F:/java-project-workspace/community/data/upload
server:
  servlet:
    context-path: /community